### ISSUE TITLE
Support alternative work titles

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-server#31]
Sometimes works are known by different names.
Being able to search work by an alternative name would be a nice improvement

**Comment by Benstales** [comment]
I'll work on this issue once I will have more free time, like in two-three weeks.
It's interesting since people often know the title of the show in their native language but not the original title (if it's, ofc, a foreign show). So it's very helpful when you are not familiar with the database of the karaoke host.

**Comment by Benstales** [comment]
I have started thinking about it.

Obviously, it's a very bad idea to put the alternative work titles in the name of the karaoke videos if there is a naming convention like in Karaneko project. This information would not only be redundant but also a nightmare to update since a work is common to different songs.

I would suggest to create an admin.py in the library folder. The manager of the database would put the alternative titles using the admin page.

As far as I know there is no admin page because you are very concerned about the design of the app. The default admin django page is well organized but looks awful. Since it is more a concern for the manager of the database, which is not your regular user, does it matter ?

btw I always find time to think about new things even when I have no time at all.

**Comment by Benstales** [comment]
Hi there,
I began to work on this. I was wondering if this is still relevant to make the distinction between titles and alternative title. Star Wars is not much more official than its old French title "La Guerre des Etoiles" for example.

Just to clarify, I add another model "WorkTitle" containing only one field "title". There is a ManyToMany relationship between Work and WorkTitle since a work can have differently titles and a title can refer to several works (Star Wars refers to Star Wars I, Star Wars II, Star Wars III). I am wondering if, in this case, it would be more relevant to replace the "title" field by a "name" field which would be mainly used for display, and add WorkTitle "titles" field which will be used to make queries.

Question time : I would like to know if there is a rule to decide which model has the ownership of the ManyToMany. Atm I give the ownership to Work, but WorkTitle is not a bad either.

**Comment by Neraste** [comment]
Good question. I think it is not that bad to have one 'main' title and (if needed) several alternative titles. Keep in mind that if there were no distinction in the back-end, there should be one at least in the front-end (*e.g.:* which title to display first, if not which one to display at all in compact view). Having a clear main name is handy for manipulation. We tried the alternative-only approach in a former version of Dakara, using a Boolean field to indicate which title is the main one, and it was a true hell.

I think a simple OneToMany is enough for our needs. A ManyToMany is more complex (it needs one extra table to store the relations) and offers little more in comparison (we will never list works for a given alternative title). When querying a work with an alternative title (which is the intended use of this field), titles and alternative titles will be matched indifferently. There will be some redundancy between the alternative titles, but I do not think this is critical for a typical use.

I think the new model's name should be a bit more specialized: `WorkAlternativeTitle`. `Work`'s `title` field should remain, the new field could be `alternative_titles`.

**Comment by Benstales** [comment]
Thanks for answering, I will work with that in mind. Since it is a OneToMany relationship it will still be coherent to dissociate the main title (a string) from the alternative titles (WorkAlternativeTitle), so I agree on the idea.

Since I have more free time, I am going to really put myself to work.

**Comment by Benstales** [comment]
Not sure about what you said about matching titles and alternatives titles indifferently. What I am about to do is editing the query title so that it includes now the alternative titles (in other words, edit views.py since there is nothing to add in the query language). Ofc I will edit the remaining query (views.py).

**Comment by Benstales** [comment]
That's quite troublesome. The queries are way too long and flake8 does not like it. `WorkAltTitle` and `alt_title` should shorten those queries, would this renaming be convenient ?

**Comment by Benstales** [comment]
A new branch has been created to adapt the feeder to take into account the alternative titles.

**Comment by Benstales** [comment]
I checked how feed.py was working. So if I understood correctly, it parses every single file in a folder specified by the user which should contain songs media files and subtitle files. From the name of those files we can extract data on those songs (with a custom parser), then we create the songs and the works, artists,... associated to these songs if they didn't exist already. So everything is fed upon the data we can extract from a "Song".

For the alternative titles, we cannot proceed the same way : it would create redundancy and we would have to update every single song name file associated to a work in order to include its alternative titles. You have to create a separate file gathering all the data about work alternative titles.

An idea would be to make a custom method like custom_parser to retrieve the data on the work alternative titles. This would let the user the choice on the file format (whether it is CSV, XML, JSON or something else...) containing such data. The only parameters required to this custom method would be the path of the file containing all the data related to work alternative titles, and the name of the work we want to retrieve the alternative titles.

**Comment by Neraste** [comment]
Now you mention it, it seems clear that the feeder is not suited to handle works extra information. As you said, the aim of the feeder is to extract data from individual song files, so dealing with an extra works file is out of its scope. I think that we should instead create a new command dedicated to this task.

We could name it `createworks` and it would get or create works (based on their name?), then add extra info to them. The idea of a custom parser is appealing if the works are stored in an exotic way, but since a JSON dump seems pretty straightforward, it could be the default parser.

**Comment by Nadeflore** [comment]
You mean, in order to gather alternative titles from work already in database, we need a way to export the list of works from the database ?

This could work, but I think we could use another approach, like instead of using a django command, we could make a script which make calls to the api, to retriever the works list and update the works with alternative titles

**Comment by Benstales** [comment]
@Nadeflore Yes I might not have been clear enough, the idea is that it is inappropriate to add the alternative titles with feed/scan method because of the reasons mentioned above, so we need to feed the database with something I call "work file" which gathers all the information about a worktype, its related works and their data (subtitle, alternative titles). To add the alternative titles with the current feed command, what I think is the natural way to do is:

- execute the feed/scan command to create works, songs, ...
- retrieve a work file such that if given to createworks command it is creating exactly the same works with the same data as the ones in the current database (or said simplier, a work file that describes the works in the current database)
- add to this work file the alternative titles for each work
- execute createworks command to update the database with the added information of the work file.

@Neraste I checked the `dumpdata` command of the django and it is working fine. So yeah, there might be no need for a `dumpdataworks` command.

**Comment by Neraste** [comment]
Was implemented long ago.
