### ISSUE TITLE
dakara-server has dependencies not compatible with Python 3.7

### ISSUE THREAD

**Issue by pjeanjean** [DakaraProject/dakara-server#76]
Using Python 3.7, PyYAML 3.12 can't even be installed with pip, and Django 1.11.13 throws SyntaxErrors.

This is definitely not urgent, but I felt like it should be reported somewhere.

Also, using Django 1.11.15 is not enough, so the issue will most likely remain until the project switches to Django 2...

**Comment by RhiobeT** [comment]
The issue with PyYAML is the one explained here: https://github.com/yaml/pyyaml/issues/126
It is solved with the version 3.13 though.

The issue with Django is a bit more tricky...
It was fixed for Django 2.0 (https://code.djangoproject.com/ticket/28814), but I doubt it will be fixed in Django 1.11.X (https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django <-- looks like Python 3.7 support is not planned for those versions)

**Comment by Neraste** [comment]
The issue with PyYAML is easy to fix.

For Django, we currently stick to the LTS versions and it it is clear that Python 3.7 is out of the scope of Django 1.11 LTS. So, either we use regular versions from now, or we wait until the next 2.* LTS version.

**Comment by Nadeflore** [comment]
Tested working with python 3.7.5 and django 1.11.23

**Comment by Neraste** [comment]
Sounds like the problem was fixed with PyYAML update and Django 1.11 updates as well.

**Comment by pjeanjean** [comment]
Great, I might update the Dockerfile to a more recent Python version then
